[package]
name = "mev_sandwich_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.10.32"  # Check for the latest version
solana-sdk = "1.10.32"      # Add this line
tokio = { version = "1", features = ["full"] }
